name: sample workflow
on:
  push:
    branches:
      - main

jobs:
  sample-job:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: ubuntu-slim
    steps:
      - name: sample-echo-command
        run: echo "🎉 congratulations!"