name: 'inputs Action'
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true
        type: string
      environment:
        description: 'The environment to deploy to'
        required: true
        type: environment
jobs: 
  print-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Print the input branch to STDOUT
      run: echo  The branch is ${{ inputs.branch }}
    - name: Print the environment
      run: echo  The environment is ${{ inputs.environment }}